### ISSUE TITLE
add text-align for --ds.copy-small

### ISSUE THREAD

**Issue by nandhinidevie** [fastn-community/design-system#10]
-- ds.container:
inset: $ds.spaces.inset-square.large
background.solid: $ds.colors.background.step-1
width.fixed.percent: 40
radius: $ds.radius.large

-- ds.heading-hero: 8%
color: blue
text-align:center ;; working

-- ds.copy-small: 
color: $ds.colors.text
text-align: center ;; not working

efficiency increase after 3 months

-- end: ds.container

![image](https://github.com/fastn-community/design-system/assets/132933318/b70c7c17-1c53-4600-874d-cb70abb764a9)

**Comment by MeenuKumari28** [comment]
Issue resolved added text-align property to every typography.

**Comment by MeenuKumari28** [comment]
Issue resolved added text-align property to every typography.
