### ISSUE TITLE
`text-align: center` is not working for `-- ds.copy-large` when used inside `-- ds.column:`

### ISSUE THREAD

**Issue by nandhinidevie** [fastn-community/design-system#9]
-- ds.column:
spacing: $ds.spaces.vertical-gap.small

-- ds.copy-large:
text-align: center
color: $ds.colors.text-strong

“CodeTogether is a really brilliant solution for ensemble coding …
especially since it integrates into different IDEs simultaneously.”

-- ds.copy-large:
text-align: center  ;; not working

Astrid Sawatzky Lead Developer, Thera-Pi

-- end: ds.column

**Comment by nandhinidevie** [comment]
![image](https://github.com/fastn-community/design-system/assets/132933318/a9ca2f8d-cfeb-46c0-be8f-4c130ba0c365)

**Comment by MeenuKumari28** [comment]
Added align-content center attribute to column.

**Comment by amitu** [comment]
@MeenuKumari28 this issue is about `text-align` on `ds.copy-large` not for `ds.column`.

**Comment by MeenuKumari28** [comment]
Added text-align property to all typographies.
